# Generated by Django 2.2.3 on 2019-09-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20190712_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('officerName', models.CharField(max_length=50)),
                ('officerPostion', models.CharField(max_length=65)),
            ],
        ),
    ]
