# Generated by Django 2.2.3 on 2019-09-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_officer_isactivte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='isActivte',
            field=models.BooleanField(default=False),
        ),
    ]
