# Generated by Django 2.2.3 on 2019-09-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_auto_20190908_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
