# Generated by Django 2.2.4 on 2020-08-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_card1_card2_card3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='card1',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='card2',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='card3',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='card1',
            name='header',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='card2',
            name='header',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='card3',
            name='header',
            field=models.CharField(max_length=40),
        ),
    ]
