# Generated by Django 2.2.4 on 2020-08-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_card1_card2_card3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card1',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='card2',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='card3',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='card1',
            name='header',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='card2',
            name='header',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='card3',
            name='header',
            field=models.CharField(max_length=40),
        ),
    ]
