# Generated by Django 2.2.4 on 2020-08-18 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_auto_20200818_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='hasBeenRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
