# Generated by Django 2.2.4 on 2020-08-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_auto_20200818_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
