# Generated by Django 2.2.4 on 2020-08-19 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0010_auto_20200818_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='unread',
            new_name='read',
        ),
    ]
