# Generated by Django 2.2.4 on 2020-08-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_auto_20200818_1604'),
        ('Projects', '0011_auto_20200818_1709'),
    ]

    operations = [
    ]
