# Generated by Django 2.2.4 on 2020-08-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0012_merge_20200818_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
